services:
  - type: web
    name: nfl-stats-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api_server:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
